### ISSUE TITLE
Notice: Use of undefined constant CONFIG_SYNC_DIRECTORY on Drupal 8.x

### ISSUE THREAD

**Issue by GuGuss** [platformsh/platformsh-example-drupal#12]
I got the following error when accessing "sites/default/settings.php": 

`Notice: Use of undefined constant CONFIG_SYNC_DIRECTORY - assumed 'CONFIG_SYNC_DIRECTORY' in /app/public/sites/default/settings.php on line 28`

**Comment by Crell** [comment]
I think this will get resolved after we swap to the composer/8.1 branch.
