### ISSUE TITLE
Needs update to Drupal 8.1?

### ISSUE THREAD

**Issue by jonathanjfshaw** [platformsh/platformsh-example-drupal#17]
projects[drupal][patch][] = https://www.drupal.org/files/issues/drupal-redirect_to_install-728702-85.patch
Patch needs reroll at the least.

**Comment by pjcdawkins** [comment]
I've re-rolled that, but I found another blocker:

* https://www.drupal.org/node/2582475

I might try to solve that in this issue: https://www.drupal.org/node/2607352

**Comment by jonathanjfshaw** [comment]
Thanks for the reroll.
#2582475 now has an RTBC patch.
#2607352 alexpott is suggesting to close in favour of https://www.drupal.org/node/2466197

**Comment by pjcdawkins** [comment]
* 2582475 has now been committed (so I guess that will be in Drupal 8.1.1), patch URL http://cgit.drupalcode.org/drupal/patch/?id=d59f27d0ccbda9fd9b7acc66f5091026bf3f781e
* 2466197 is still making progress

**Comment by jonathanjfshaw** [comment]
https://www.drupal.org/files/issues/2466197-29.patch seems mature now. So it looks like we have the patches needed for a clean install of 8.1 on platform.sh?

**Comment by jordila** [comment]
Does it means that adding
```
projects[drupal][patch][] = "https://drupal.org/files/issues/install-redirect-on-empty-database-728702-36.patch"
```
...to .make file (or something like)... should do the job ?

**Comment by pjcdawkins** [comment]
@jonathanjfshaw

**Comment by pjcdawkins** [comment]
Oops, I did not mean to close this, I wanted to click "Cancel"... I'm working on this today.

**Comment by Crell** [comment]
The new composer-based template we just deployed is using Drupal 8.1.2, so we're good here, and it should be easier to keep up to date in the future.  Thanks all!
