### ISSUE TITLE
updatedb before config-import

### ISSUE THREAD

**Issue by jonathanjfshaw** [platformsh/platformsh-example-drupal#29]
According to https://www.drupal.org/node/2628144 (see comments 29 & 30), drush updatedb should happen before drush config-import, otherwise there are risks to config integrity.

In .platform.app.yml, you have them the other way round.

**Comment by pjcdawkins** [comment]
OK, I think you're right.

But IIRC the current config (https://github.com/platformsh/platformsh-example-drupal/blob/8.x/.platform.app.yaml#L63-L65) was arrived at after discussion with @floretan and/or @Berdir so I'd like to hear their input.

Cc @Crell @Kazanir

**Comment by Berdir** [comment]
Yes, this is correct, it's not allowed to do a config import with different module versions, Drupal core will eventually validate that.

I would even go as far as to say that you shouldn't do both at the same time unless you verified that there is no problem. There's always the risk that there are conflicts. update functions might make changes that don't result in the same every time you run them. (For example, different UUID's when creating config entities). The result is that the config import could delete and re-create config entities, which could lead to data loss (e.g. when fields are deleted and re-created) or other problems.

**Comment by pjcdawkins** [comment]
"Verifying that there is no problem" is what Platform.sh development environments are for :) Well that, and automated functional testing.

**Comment by Crell** [comment]
The fix has been merged. Thanks!
